create table flights
(
    id               bigint generated by default as identity
        primary key,
    arrival          varchar(255) not null,
    departure        varchar(255) not null,
    maximum_capacity integer      not null,
    constraint u_departure_arrival
        unique (departure, arrival)
);

alter table flights
    owner to postgres;

create table scheduled_flights
(
    id             bigint generated by default as identity
        primary key,
    departure_date date   not null,
    flight_id      bigint not null
        constraint fkb16n1nrr1ehmjc32a6bv8d18d
            references flights,
    constraint u_flight_date
        unique (flight_id, departure_date)
);

alter table scheduled_flights
    owner to postgres;

create table users
(
    id       bigint generated by default as identity
        primary key,
    password varchar(255),
    username varchar(255) not null
        constraint ukr43af9ap4edm43mmtq01oddj6
            unique
);

alter table users
    owner to postgres;

create table bookings
(
    id                  bigint generated by default as identity
        primary key,
    seats               integer not null,
    scheduled_flight_id bigint  not null
        constraint fkn3auba9uc8l4otqw9wkalmdrg
            references scheduled_flights,
    user_id             bigint  not null
        constraint fkeyog2oic85xg7hsu2je2lx3s6
            references users
);

alter table bookings
    owner to postgres;

create index idx_booking_scheduled_flight
    on bookings (scheduled_flight_id);



-- Flights
INSERT INTO flights (departure, arrival, maximum_capacity) VALUES ('EBBR', 'LFMN', 120);
INSERT INTO flights (departure, arrival, maximum_capacity) VALUES ('EBBR', 'LFML', 115);
INSERT INTO flights (departure, arrival, maximum_capacity) VALUES ('EBBR', 'LSGG', 95);
INSERT INTO flights (departure, arrival, maximum_capacity) VALUES ('LFMN', 'EBBR', 120);
INSERT INTO flights (departure, arrival, maximum_capacity) VALUES ('EBBR', 'KJFK', 190);
INSERT INTO flights (departure, arrival, maximum_capacity) VALUES ('KJFK', 'EBBR', 190);

-- Scheduled flights
-- EBBR LFMN
INSERT INTO scheduled_flights (flight_id, departure_date) VALUES ((SELECT id FROM flights WHERE departure = 'EBBR' AND arrival = 'LFMN'), CURRENT_DATE - INTERVAL '1 day');
INSERT INTO scheduled_flights (flight_id, departure_date) VALUES ((SELECT id FROM flights WHERE departure = 'EBBR' AND arrival = 'LFMN'), CURRENT_DATE);
INSERT INTO scheduled_flights (flight_id, departure_date) VALUES ((SELECT id FROM flights WHERE departure = 'EBBR' AND arrival = 'LFMN'), CURRENT_DATE + INTERVAL '1 day');
INSERT INTO scheduled_flights (flight_id, departure_date) VALUES ((SELECT id FROM flights WHERE departure = 'EBBR' AND arrival = 'LFMN'), CURRENT_DATE + INTERVAL '7 days');
INSERT INTO scheduled_flights (flight_id, departure_date) VALUES ((SELECT id FROM flights WHERE departure = 'EBBR' AND arrival = 'LFMN'), CURRENT_DATE + INTERVAL '8 days');
-- EBBR LFML
INSERT INTO scheduled_flights (flight_id, departure_date) VALUES ((SELECT id FROM flights WHERE departure = 'EBBR' AND arrival = 'LFML'), CURRENT_DATE + INTERVAL '2 days');
INSERT INTO scheduled_flights (flight_id, departure_date) VALUES ((SELECT id FROM flights WHERE departure = 'EBBR' AND arrival = 'LFML'), CURRENT_DATE + INTERVAL '14 days');
-- EBBR KJFK
INSERT INTO scheduled_flights (flight_id, departure_date) VALUES ((SELECT id FROM flights WHERE departure = 'EBBR' AND arrival = 'KJFK'), CURRENT_DATE - INTERVAL '7 days');
INSERT INTO scheduled_flights (flight_id, departure_date) VALUES ((SELECT id FROM flights WHERE departure = 'EBBR' AND arrival = 'KJFK'), CURRENT_DATE + INTERVAL '1 day');
INSERT INTO scheduled_flights (flight_id, departure_date) VALUES ((SELECT id FROM flights WHERE departure = 'EBBR' AND arrival = 'KJFK'), CURRENT_DATE + INTERVAL '7 days');
-- KJFK EBBR
INSERT INTO scheduled_flights (flight_id, departure_date) VALUES ((SELECT id FROM flights WHERE departure = 'KJFK' AND arrival = 'EBBR'), CURRENT_DATE + INTERVAL '3 days');

-- Test user
INSERT INTO users (username, password) VALUES ('test', '$2a$10$25FMNZLir77nSGmMYqudvu5Eirr4LFUykiylpH6.7wcUJkii2huU2');
INSERT INTO users (username, password) VALUES ('test-2', '$2a$10$25FMNZLir77nSGmMYqudvu5Eirr4LFUykiylpH6.7wcUJkii2huU2');

-- Existing bookings
INSERT INTO bookings (seats, scheduled_flight_id, user_id) VALUES (120, (SELECT id FROM scheduled_flights WHERE flight_id = (SELECT id FROM flights WHERE departure = 'EBBR' AND arrival = 'LFMN') AND departure_date = CURRENT_DATE + INTERVAL '7 days'), (SELECT id FROM users WHERE username = 'test'));
INSERT INTO bookings (seats, scheduled_flight_id, user_id) VALUES (118, (SELECT id FROM scheduled_flights WHERE flight_id = (SELECT id FROM flights WHERE departure = 'EBBR' AND arrival = 'LFMN') AND departure_date = CURRENT_DATE + INTERVAL '8 days'), (SELECT id FROM users WHERE username = 'test'));
INSERT INTO bookings (seats, scheduled_flight_id, user_id) VALUES (189, (SELECT id FROM scheduled_flights WHERE flight_id = (SELECT id FROM flights WHERE departure = 'EBBR' AND arrival = 'KJFK') AND departure_date = CURRENT_DATE + INTERVAL '7 days'), (SELECT id FROM users WHERE username = 'test-2'));

