DELETE FROM bookings;
DELETE FROM scheduled_flights;
DELETE FROM flights;
DELETE FROM users;

SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE bookings RESTART IDENTITY;
TRUNCATE TABLE scheduled_flights RESTART IDENTITY;
TRUNCATE TABLE flights RESTART IDENTITY;
TRUNCATE TABLE users RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;